// export const API_ENDPOINT = '/api';
// export const AUTH_ENDPOINT = API_ENDPOINT;

export const API_ENDPOINT = 'http://localhost:3000/api';
export const AUTH_ENDPOINT = API_ENDPOINT;

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_POLL_SUCCESS = 'LOAD_POLL_SUCCESS';
export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
export const CREATE_POLL_FAILURE = 'CREATE_POLL_FAILURE';
export const UPDATE_POLL_SUCCESS = 'UPDATE_POLL_SUCCESS';

export const DELETE_POLL_SUCCESS = 'DELETE_POLL_SUCCESS';
export const DELETE_POLL_FAILURE = 'DELETE_POLL_FAILURE';

export const LOAD_POLL_FAILURE = 'LOAD_POLL_FAILURE';

export const POLL_VOTE_SUCCESS = 'POLL_VOTE_SUCCESS';
export const POLL_VOTE_FAILURE = 'POLL_VOTE_FAILURE';

export const LOAD_POLLS_REQUEST = 'LOAD_POLLS_REQUEST';
export const LOAD_POLLS_SUCCESS = 'LOAD_POLLS_SUCCESS';
export const LOAD_POLLS_FAILURE = 'LOAD_POLLS_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
