export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_POLL_SUCCESS = 'LOAD_POLL_SUCCESS';
export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
export const UPDATE_POLL_SUCCESS = 'UPDATE_POLL_SUCCESS';
export const DELETE_POLL_SUCCESS = 'DELETE_POLL_SUCCESS';

export const LOAD_POLLS_SUCCESS = 'LOAD_POLLS_SUCCESS';
export const CREATE_POLLS_SUCCESS = 'CREATE_POLLS_SUCCESS';
export const UPDATE_POLLS_SUCCESS = 'UPDATE_POLLS_SUCCESS';
export const DELETE_POLLS_SUCCESS = 'DELETE_POLLS_SUCCESS';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
